apiVersion: v1
kind: Service
metadata:
  name: debian-srv
  namespace: test-ns
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: debian
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debian
  namespace: test-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debian
  template:
    metadata:
          labels:
            app: debian
    spec:
      containers:
      - image: nginx
        name: debian
        ports:
        - containerPort: 80
          protocol: TCP
