apiVersion: v1
kind: Service
metadata:
  name: debian-srv
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: debian
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debian
spec:
  replicas: 6
  selector:
    matchLabels:
      app: debian
  template:
    metadata:
          labels:
            app: debian
    spec:
      containers:
      - image: nginx
        name: debian
        resources:
          requests:
            memory: "50Mi"
          limits:
            memory: "512Mi"
        ports:
        - containerPort: 80
          protocol: TCP
