apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: morty-ingress
  namespace: morty
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - morty.example.com
    secretName: tls-secret
  rules:
  - host: morty.example.com
    http:
      paths:
      - backend:
          serviceName: nginx-2-srv
          servicePort: 80
