apiVersion: v1
kind: Service
metadata:
  name: nginx-3-srv
  namespace: test-ns
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx-3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-3
  namespace: test-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-3
  template:
    metadata:
          labels:
            app: nginx-3
    spec:
      containers:
      - image: nginx
        name: nginx-3
        ports:
        - containerPort: 80
          protocol: TCP
