apiVersion: v1
kind: Service
metadata:
  name: nginx-2-srv
  namespace: rick
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
  selector:
    app: nginx-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-2
  namespace: rick
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-2
  template:
    metadata:
          labels:
            app: nginx-2
    spec:
      containers:
      - image: httpd
        name: nginx-2
        ports:
        - containerPort: 80
          protocol: TCP
