apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cluster-ingress
  namespace: infra
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - morty.example.com
    secretName: tls-secret
  - hosts:
    - rick.example.com
    secretName: tls-secret
  rules:
  - host: morty.example.com
    http:
      paths:
      - backend:
          serviceName: nginx-2-srv
          servicePort: 80
  - host: rick.example.com
    http:
      paths:
      - backend:
          serviceName: gotest-app-rick
          servicePort: 8080
