apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-loadbalancer
  namespace: nginx-ingress
  # annotations:
    # service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: nginx-ingress
