apiVersion: v1
kind: Service
metadata:
  name: fastcgi-$DEPLOY_TAG
  namespace: $DEPLOY_TAG
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: fastcgi-$DEPLOY_TAG
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fastcgi-autoscaler-$DEPLOY_TAG
  namespace: $DEPLOY_TAG
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fastcgi-$DEPLOY_TAG
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastcgi-$DEPLOY_TAG
  namespace: $DEPLOY_TAG
spec:
  replicas: 5
  selector:
    matchLabels:
      app: fastcgi-$DEPLOY_TAG
  template:
    metadata:
      labels:
        app: fastcgi-$DEPLOY_TAG
        digest: $IMAGE_DIGEST
    spec:
      containers:
      - image: reloni/fastcgi:$DEPLOY_TAG
        imagePullPolicy: Always
        name: fastcgi-$DEPLOY_TAG
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 9000
          protocol: fastcgi
