apiVersion: v1
kind: Service
metadata:
  name: fastcgi-$DEPLOY_TAG
  namespace: $DEPLOY_TAG
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: fastcgi-$DEPLOY_TAG
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fastcgi-autoscaler-$DEPLOY_TAG
  namespace: $DEPLOY_TAG
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fastcgi-$DEPLOY_TAG
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fastcgi-configmap-$DEPLOY_TAG
data:
  SCRIPT_FILENAME: "/example/index.php"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $DEPLOY_TAG-ingress-fastcgi
  namespace: $DEPLOY_TAG
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "FCGI"
    nginx.ingress.kubernetes.io/fastcgi-index: "index.php"
    nginx.ingress.kubernetes.io/fastcgi-params-configmap: "fastcgi-configmap-$DEPLOY_TAG"
spec:
  tls:
  - hosts:
    - "fpm.$DEPLOY_TAG.alpinadigital.rocks"
    secretName: ad-rocks-widlcard
  rules:
  - host: "fpm.$DEPLOY_TAG.alpinadigital.rocks"
    http:
      paths:
      - path: /
        backend:
          serviceName: fastcgi-$DEPLOY_TAG
          servicePort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastcgi-$DEPLOY_TAG
  namespace: $DEPLOY_TAG
spec:
  replicas: 5
  selector:
    matchLabels:
      app: fastcgi-$DEPLOY_TAG
  template:
    metadata:
      labels:
        app: fastcgi-$DEPLOY_TAG
        digest: $IMAGE_DIGEST
    spec:
      containers:
      - image: reloni/fastcgi:$DEPLOY_TAG
        imagePullPolicy: Always
        name: fastcgi-$DEPLOY_TAG
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 9000
          protocol: fastcgi
