apiVersion: v1
kind: Service
metadata:
  name: go-static-files-$DEPLOY_TAG
  namespace: $DEPLOY_TAG
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: go-static-files-$DEPLOY_TAG
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-static-files-$DEPLOY_TAG
  namespace: $DEPLOY_TAG
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-static-files-$DEPLOY_TAG
  template:
    metadata:
      labels:
        app: go-static-files-$DEPLOY_TAG
        digest: $IMAGE_DIGEST
    spec:
      containers:
      - image: reloni/go-static-files:$DEPLOY_TAG
        imagePullPolicy: Always
        name: go-static-files-$DEPLOY_TAG
        securityContext:
          runAsNonRoot: true
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        ports:
        - containerPort: 8080
          protocol: TCP
