apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: $DEPLOY_TAG
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: gotest-redis-$DEPLOY_TAG
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotest-redis-$DEPLOY_TAG
  namespace: $DEPLOY_TAG
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotest-redis-$DEPLOY_TAG
  template:
    metadata:
      labels:
        app: gotest-redis-$DEPLOY_TAG
    spec:
      containers:
      - image: reloni/goexample-redis:$DEPLOY_TAG
        imagePullPolicy: Always
        name: gotest-redis-$DEPLOY_TAG
        ports:
        - containerPort: 6379
          protocol: TCP
