apiVersion: v1
kind: Service
metadata:
  name: gotest-redis-$CI_COMMIT_REF_NAME
  namespace: $CI_COMMIT_REF_NAME
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: gotest-app-$CI_COMMIT_REF_NAME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotest-app
  namespace: $CI_COMMIT_REF_NAME
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gotest-app
  template:
    metadata:
      labels:
        app: gotest-app
    spec:
      containers:
      - image: reloni/goexample:$GOTEST_TAG
        name: gotest-app
        ports:
        - containerPort: 8080
          protocol: TCP
