apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $NAMESPACE-ingress-wildcard
  namespace: $NAMESPACE
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/server-snippets: |
      gzip on;
      gzip_http_version 1.1;
      gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
      server_name *.$NAMESPACE.alpinadigital.rocks;
spec:
  tls:
  - hosts:
    - "$NAMESPACE.alpinadigital.rocks"
    secretName: ad-rocks-widlcard
  rules:
  - host: "$NAMESPACE.alpinadigital.rocks"
    http:
      paths:
      - path: /
        backend:
          serviceName: gotest-app-$NAMESPACE
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $NAMESPACE-ingress-static
  namespace: $NAMESPACE
  annotations:
    kubernetes.io/ingress.class: nginx
    #service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
    #nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    #nginx.ingress.kubernetes.io/ssl-redirect: "true"
    #service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
    nginx.org/server-snippets: |
      gzip on;
      gzip_http_version 1.1;
      gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
spec:
  tls:
  - hosts:
    - "static.$NAMESPACE.alpinadigital.rocks"
    secretName: ad-rocks-static-$NAMESPACE
  rules:
  - host: "static.$NAMESPACE.alpinadigital.rocks"
    http:
      paths:
      - path: /
        backend:
          serviceName: go-static-files-$NAMESPACE
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $NAMESPACE-ingress-files
  namespace: $NAMESPACE
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/server-snippets: |
      gzip on;
      gzip_http_version 1.1;
      gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
      client_max_body_size 150m;
spec:
  tls:
  - hosts:
    - "files.$NAMESPACE.alpinadigital.rocks"
    secretName: ad-rocks-widlcard
  rules:
  - host: "files.$NAMESPACE.alpinadigital.rocks"
    http:
      paths:
      - path: /
        backend:
          serviceName: files-minio-$NAMESPACE
          servicePort: 80
