apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $DEPLOY_TAG-ingress
  namespace: $DEPLOY_TAG
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - $DEPLOY_TAG.example.com
    secretName: tls-secret
  rules:
  - host: $DEPLOY_TAG.example.com
    http:
      paths:
      - backend:
          serviceName: gotest-app-$DEPLOY_TAG
          servicePort: 8080
