apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $NAMESPACE-ingress-wildcard
  namespace: $NAMESPACE
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/server-snippet: |
      server_name *.$NAMESPACE.alpinadigital.rocks;
spec:
  tls:
  - hosts:
    - "$NAMESPACE.alpinadigital.rocks"
    secretName: ad-rocks-widlcard
  rules:
  - host: "$NAMESPACE.alpinadigital.rocks"
    http:
      paths:
      - path: /
        backend:
          serviceName: gotest-app-$NAMESPACE
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $NAMESPACE-ingress-static
  namespace: $NAMESPACE
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - "static.$NAMESPACE.alpinadigital.rocks"
    secretName: ad-rocks-static-$NAMESPACE
  rules:
  - host: "static.$NAMESPACE.alpinadigital.rocks"
    http:
      paths:
      - path: /
        backend:
          serviceName: go-static-files-$NAMESPACE
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $NAMESPACE-ingress-files
  namespace: $NAMESPACE
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "512m"
spec:
  tls:
  - hosts:
    - "files.$NAMESPACE.alpinadigital.rocks"
    secretName: ad-rocks-widlcard
  rules:
  - host: "files.$NAMESPACE.alpinadigital.rocks"
    http:
      paths:
      - path: /
        backend:
          serviceName: files-minio-$NAMESPACE
          servicePort: 80
