apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $CI_COMMIT_REF_NAME-ingress
  namespace: $CI_COMMIT_REF_NAME
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - $CI_COMMIT_REF_NAME.example.com
    secretName: tls-secret
  rules:
  - host: $CI_COMMIT_REF_NAME.example.com
    http:
      paths:
      - backend:
          serviceName: gotest-app-$CI_COMMIT_REF_NAME
          servicePort: 80
