kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: $NAMESPACE-user-full-access-$USER_ID
  namespace: $NAMESPACE
subjects:
- kind: User
  name: $USER_ID
  namespace: $NAMESPACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: $NAMESPACE-user-full-access
